# Generated by Django 5.0.4 on 2024-04-23 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='MenuItems',
        ),
    ]
