# Generated by Django 5.0.4 on 2024-04-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantAPI', '0002_rename_menu_menuitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
