# Generated by Django 5.0.4 on 2024-05-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurantAPI", "0005_menuitems"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitems",
            name="Discrption",
            field=models.TextField(default="", max_length=255),
        ),
    ]
