# Generated by Django 5.0.6 on 2024-05-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurantAPI", "0006_menuitems_discrption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="Booking_date",
            field=models.DateField(),
        ),
    ]
