# Generated by Django 5.0.6 on 2024-05-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurantAPI", "0008_rename_booking_date_booking_booking_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="booking_date",
            new_name="reservation_date",
        ),
        migrations.AddField(
            model_name="booking",
            name="reservation_slot",
            field=models.IntegerField(default=10),
        ),
    ]
